name: portfolio
description: "A Mario-style car game portfolio."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2  # Add this line
  font_awesome_flutter: ^9.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/car_man1.png
    - assets/images/clouds.png
    - assets/images/grass_floor.png
    - assets/images/sky.png
    - assets/images/signpost-home.png
    - assets/images/signpost-skills.png
    - assets/images/signpost-leadership.png
    - assets/images/signpost-experience.png
    - assets/images/signpost-project.png
    - assets/images/signpost-aboutme.png
    - assets/images/profile.png
    - assets/images/about_button.png
    - assets/images/experience_button.png
    - assets/images/projects_button.png
    - assets/images/click_me.png